//Auto-generated by kalyptus. DO NOT EDIT.
namespace Soprano.Vocabulary.OWL {

	using Soprano;
	using System;
	using Qyoto;




	[SmokeClass("Soprano::Vocabulary::OWL")]
	public class Global {
		private static SmokeInvocation staticInterceptor = null;
		static Global() {
			staticInterceptor = new SmokeInvocation(typeof(Global), null);
		}
		/// <remarks>
		///  http://www.w3.org/2002/07/owl#
		///              </remarks>		<short>    http://www.</short>
		public static QUrl OwlNamespace() {
			return (QUrl) staticInterceptor.Invoke("owlNamespace", "owlNamespace()", typeof(QUrl));
		}
		/// <remarks>
		///  http://www.w3.org/2002/07/owl#AllDifferent 
		///              </remarks>		<short>    http://www.</short>
		public static QUrl AllDifferent() {
			return (QUrl) staticInterceptor.Invoke("AllDifferent", "AllDifferent()", typeof(QUrl));
		}
		/// <remarks>
		///  http://www.w3.org/2002/07/owl#AnnotationProperty 
		///              </remarks>		<short>    http://www.</short>
		public static QUrl AnnotationProperty() {
			return (QUrl) staticInterceptor.Invoke("AnnotationProperty", "AnnotationProperty()", typeof(QUrl));
		}
		/// <remarks>
		///  http://www.w3.org/2002/07/owl#Class 
		///              </remarks>		<short>    http://www.</short>
		public static QUrl Class() {
			return (QUrl) staticInterceptor.Invoke("Class", "Class()", typeof(QUrl));
		}
		/// <remarks>
		///  http://www.w3.org/2002/07/owl#DataRange 
		///              </remarks>		<short>    http://www.</short>
		public static QUrl DataRange() {
			return (QUrl) staticInterceptor.Invoke("DataRange", "DataRange()", typeof(QUrl));
		}
		/// <remarks>
		///  http://www.w3.org/2002/07/owl#DatatypeProperty 
		///              </remarks>		<short>    http://www.</short>
		public static QUrl DatatypeProperty() {
			return (QUrl) staticInterceptor.Invoke("DatatypeProperty", "DatatypeProperty()", typeof(QUrl));
		}
		/// <remarks>
		///  http://www.w3.org/2002/07/owl#DeprecatedClass 
		///              </remarks>		<short>    http://www.</short>
		public static QUrl DeprecatedClass() {
			return (QUrl) staticInterceptor.Invoke("DeprecatedClass", "DeprecatedClass()", typeof(QUrl));
		}
		/// <remarks>
		///  http://www.w3.org/2002/07/owl#DeprecatedProperty 
		///              </remarks>		<short>    http://www.</short>
		public static QUrl DeprecatedProperty() {
			return (QUrl) staticInterceptor.Invoke("DeprecatedProperty", "DeprecatedProperty()", typeof(QUrl));
		}
		/// <remarks>
		///  http://www.w3.org/2002/07/owl#FunctionalProperty 
		///              </remarks>		<short>    http://www.</short>
		public static QUrl FunctionalProperty() {
			return (QUrl) staticInterceptor.Invoke("FunctionalProperty", "FunctionalProperty()", typeof(QUrl));
		}
		/// <remarks>
		///  http://www.w3.org/2002/07/owl#InverseFunctionalProperty 
		///              </remarks>		<short>    http://www.</short>
		public static QUrl InverseFunctionalProperty() {
			return (QUrl) staticInterceptor.Invoke("InverseFunctionalProperty", "InverseFunctionalProperty()", typeof(QUrl));
		}
		/// <remarks>
		///  http://www.w3.org/2002/07/owl#Nothing 
		///              </remarks>		<short>    http://www.</short>
		public static QUrl Nothing() {
			return (QUrl) staticInterceptor.Invoke("Nothing", "Nothing()", typeof(QUrl));
		}
		/// <remarks>
		///  http://www.w3.org/2002/07/owl#ObjectProperty 
		///              </remarks>		<short>    http://www.</short>
		public static QUrl ObjectProperty() {
			return (QUrl) staticInterceptor.Invoke("ObjectProperty", "ObjectProperty()", typeof(QUrl));
		}
		/// <remarks>
		///  http://www.w3.org/2002/07/owl#Ontology 
		///              </remarks>		<short>    http://www.</short>
		public static QUrl Ontology() {
			return (QUrl) staticInterceptor.Invoke("Ontology", "Ontology()", typeof(QUrl));
		}
		/// <remarks>
		///  http://www.w3.org/2002/07/owl#OntologyProperty 
		///              </remarks>		<short>    http://www.</short>
		public static QUrl OntologyProperty() {
			return (QUrl) staticInterceptor.Invoke("OntologyProperty", "OntologyProperty()", typeof(QUrl));
		}
		/// <remarks>
		///  http://www.w3.org/2002/07/owl#Restriction 
		///              </remarks>		<short>    http://www.</short>
		public static QUrl Restriction() {
			return (QUrl) staticInterceptor.Invoke("Restriction", "Restriction()", typeof(QUrl));
		}
		/// <remarks>
		///  http://www.w3.org/2002/07/owl#SymmetricProperty 
		///              </remarks>		<short>    http://www.</short>
		public static QUrl SymmetricProperty() {
			return (QUrl) staticInterceptor.Invoke("SymmetricProperty", "SymmetricProperty()", typeof(QUrl));
		}
		/// <remarks>
		///  http://www.w3.org/2002/07/owl#Thing 
		///              </remarks>		<short>    http://www.</short>
		public static QUrl Thing() {
			return (QUrl) staticInterceptor.Invoke("Thing", "Thing()", typeof(QUrl));
		}
		/// <remarks>
		///  http://www.w3.org/2002/07/owl#TransitiveProperty 
		///              </remarks>		<short>    http://www.</short>
		public static QUrl TransitiveProperty() {
			return (QUrl) staticInterceptor.Invoke("TransitiveProperty", "TransitiveProperty()", typeof(QUrl));
		}
		/// <remarks>
		///  http://www.w3.org/2002/07/owl#allValuesFrom 
		///              </remarks>		<short>    http://www.</short>
		public static QUrl AllValuesFrom() {
			return (QUrl) staticInterceptor.Invoke("allValuesFrom", "allValuesFrom()", typeof(QUrl));
		}
		/// <remarks>
		///  http://www.w3.org/2002/07/owl#backwardCompatibleWith 
		///              </remarks>		<short>    http://www.</short>
		public static QUrl BackwardCompatibleWith() {
			return (QUrl) staticInterceptor.Invoke("backwardCompatibleWith", "backwardCompatibleWith()", typeof(QUrl));
		}
		/// <remarks>
		///  http://www.w3.org/2002/07/owl#cardinality 
		///              </remarks>		<short>    http://www.</short>
		public static QUrl Cardinality() {
			return (QUrl) staticInterceptor.Invoke("cardinality", "cardinality()", typeof(QUrl));
		}
		/// <remarks>
		///  http://www.w3.org/2002/07/owl#complementOf 
		///              </remarks>		<short>    http://www.</short>
		public static QUrl ComplementOf() {
			return (QUrl) staticInterceptor.Invoke("complementOf", "complementOf()", typeof(QUrl));
		}
		/// <remarks>
		///  http://www.w3.org/2002/07/owl#differentFrom 
		///              </remarks>		<short>    http://www.</short>
		public static QUrl DifferentFrom() {
			return (QUrl) staticInterceptor.Invoke("differentFrom", "differentFrom()", typeof(QUrl));
		}
		/// <remarks>
		///  http://www.w3.org/2002/07/owl#disjointWith 
		///              </remarks>		<short>    http://www.</short>
		public static QUrl DisjointWith() {
			return (QUrl) staticInterceptor.Invoke("disjointWith", "disjointWith()", typeof(QUrl));
		}
		/// <remarks>
		///  http://www.w3.org/2002/07/owl#distinctMembers 
		///              </remarks>		<short>    http://www.</short>
		public static QUrl DistinctMembers() {
			return (QUrl) staticInterceptor.Invoke("distinctMembers", "distinctMembers()", typeof(QUrl));
		}
		/// <remarks>
		///  http://www.w3.org/2002/07/owl#equivalentClass 
		///              </remarks>		<short>    http://www.</short>
		public static QUrl EquivalentClass() {
			return (QUrl) staticInterceptor.Invoke("equivalentClass", "equivalentClass()", typeof(QUrl));
		}
		/// <remarks>
		///  http://www.w3.org/2002/07/owl#equivalentProperty 
		///              </remarks>		<short>    http://www.</short>
		public static QUrl EquivalentProperty() {
			return (QUrl) staticInterceptor.Invoke("equivalentProperty", "equivalentProperty()", typeof(QUrl));
		}
		/// <remarks>
		///  http://www.w3.org/2002/07/owl#hasValue 
		///              </remarks>		<short>    http://www.</short>
		public static QUrl HasValue() {
			return (QUrl) staticInterceptor.Invoke("hasValue", "hasValue()", typeof(QUrl));
		}
		/// <remarks>
		///  http://www.w3.org/2002/07/owl#imports 
		///              </remarks>		<short>    http://www.</short>
		public static QUrl Imports() {
			return (QUrl) staticInterceptor.Invoke("imports", "imports()", typeof(QUrl));
		}
		/// <remarks>
		///  http://www.w3.org/2002/07/owl#incompatibleWith 
		///              </remarks>		<short>    http://www.</short>
		public static QUrl IncompatibleWith() {
			return (QUrl) staticInterceptor.Invoke("incompatibleWith", "incompatibleWith()", typeof(QUrl));
		}
		/// <remarks>
		///  http://www.w3.org/2002/07/owl#intersectionOf 
		///              </remarks>		<short>    http://www.</short>
		public static QUrl IntersectionOf() {
			return (QUrl) staticInterceptor.Invoke("intersectionOf", "intersectionOf()", typeof(QUrl));
		}
		/// <remarks>
		///  http://www.w3.org/2002/07/owl#inverseOf 
		///              </remarks>		<short>    http://www.</short>
		public static QUrl InverseOf() {
			return (QUrl) staticInterceptor.Invoke("inverseOf", "inverseOf()", typeof(QUrl));
		}
		/// <remarks>
		///  http://www.w3.org/2002/07/owl#maxCardinality 
		///              </remarks>		<short>    http://www.</short>
		public static QUrl MaxCardinality() {
			return (QUrl) staticInterceptor.Invoke("maxCardinality", "maxCardinality()", typeof(QUrl));
		}
		/// <remarks>
		///  http://www.w3.org/2002/07/owl#minCardinality 
		///              </remarks>		<short>    http://www.</short>
		public static QUrl MinCardinality() {
			return (QUrl) staticInterceptor.Invoke("minCardinality", "minCardinality()", typeof(QUrl));
		}
		/// <remarks>
		///  http://www.w3.org/2002/07/owl#onProperty 
		///              </remarks>		<short>    http://www.</short>
		public static QUrl OnProperty() {
			return (QUrl) staticInterceptor.Invoke("onProperty", "onProperty()", typeof(QUrl));
		}
		/// <remarks>
		///  http://www.w3.org/2002/07/owl#oneOf 
		///              </remarks>		<short>    http://www.</short>
		public static QUrl OneOf() {
			return (QUrl) staticInterceptor.Invoke("oneOf", "oneOf()", typeof(QUrl));
		}
		/// <remarks>
		///  http://www.w3.org/2002/07/owl#priorVersion 
		///              </remarks>		<short>    http://www.</short>
		public static QUrl PriorVersion() {
			return (QUrl) staticInterceptor.Invoke("priorVersion", "priorVersion()", typeof(QUrl));
		}
		/// <remarks>
		///  http://www.w3.org/2002/07/owl#sameAs 
		///              </remarks>		<short>    http://www.</short>
		public static QUrl SameAs() {
			return (QUrl) staticInterceptor.Invoke("sameAs", "sameAs()", typeof(QUrl));
		}
		/// <remarks>
		///  http://www.w3.org/2002/07/owl#someValuesFrom 
		///              </remarks>		<short>    http://www.</short>
		public static QUrl SomeValuesFrom() {
			return (QUrl) staticInterceptor.Invoke("someValuesFrom", "someValuesFrom()", typeof(QUrl));
		}
		/// <remarks>
		///  http://www.w3.org/2002/07/owl#unionOf 
		///              </remarks>		<short>    http://www.</short>
		public static QUrl UnionOf() {
			return (QUrl) staticInterceptor.Invoke("unionOf", "unionOf()", typeof(QUrl));
		}
		/// <remarks>
		///  http://www.w3.org/2002/07/owl#versionInfo 
		///              </remarks>		<short>    http://www.</short>
		public static QUrl VersionInfo() {
			return (QUrl) staticInterceptor.Invoke("versionInfo", "versionInfo()", typeof(QUrl));
		}
	}
}
