//Auto-generated by ../../kalyptus/kalyptus. DO NOT EDIT.
namespace Qt {

	using System;
	using System.Text;

	/// See <see cref="IQCheckBoxSignals"></see> for signals emitted by QCheckBox
	public class QCheckBox : QAbstractButton, IDisposable {
 		protected QCheckBox(Type dummy) : base((Type) null) {}
		interface IQCheckBoxProxy {
			string Tr(string s, string c);
			string Tr(string s);
		}

		protected void CreateQCheckBoxProxy() {
			SmokeInvocation realProxy = new SmokeInvocation(typeof(QCheckBox), this);
			_interceptor = (QCheckBox) realProxy.GetTransparentProxy();
		}
		private QCheckBox ProxyQCheckBox() {
			return (QCheckBox) _interceptor;
		}
		private static Object _staticInterceptor = null;
		static QCheckBox() {
			SmokeInvocation realProxy = new SmokeInvocation(typeof(IQCheckBoxProxy), null);
			_staticInterceptor = (IQCheckBoxProxy) realProxy.GetTransparentProxy();
		}
		private static IQCheckBoxProxy StaticQCheckBox() {
			return (IQCheckBoxProxy) _staticInterceptor;
		}

		public new virtual QMetaObject MetaObject() {
			return ProxyQCheckBox().MetaObject();
		}
		// void* qt_metacast(const char* arg1); >>>> NOT CONVERTED
		// int qt_metacall(QMetaObject::Call arg1,int arg2,void** arg3); >>>> NOT CONVERTED
		public QCheckBox(QWidget parent) : this((Type) null) {
			CreateQCheckBoxProxy();
			NewQCheckBox(parent);
		}
		private void NewQCheckBox(QWidget parent) {
			ProxyQCheckBox().NewQCheckBox(parent);
		}
		public QCheckBox() : this((Type) null) {
			CreateQCheckBoxProxy();
			NewQCheckBox();
		}
		private void NewQCheckBox() {
			ProxyQCheckBox().NewQCheckBox();
		}
		public QCheckBox(string text, QWidget parent) : this((Type) null) {
			CreateQCheckBoxProxy();
			NewQCheckBox(text,parent);
		}
		private void NewQCheckBox(string text, QWidget parent) {
			ProxyQCheckBox().NewQCheckBox(text,parent);
		}
		public QCheckBox(string text) : this((Type) null) {
			CreateQCheckBoxProxy();
			NewQCheckBox(text);
		}
		private void NewQCheckBox(string text) {
			ProxyQCheckBox().NewQCheckBox(text);
		}
		public new QSize SizeHint() {
			return ProxyQCheckBox().SizeHint();
		}
		public void SetTristate(bool y) {
			ProxyQCheckBox().SetTristate(y);
		}
		public void SetTristate() {
			ProxyQCheckBox().SetTristate();
		}
		public bool IsTristate() {
			return ProxyQCheckBox().IsTristate();
		}
		public int CheckState() {
			return ProxyQCheckBox().CheckState();
		}
		public void SetCheckState(int state) {
			ProxyQCheckBox().SetCheckState(state);
		}
		public static new string Tr(string s, string c) {
			return StaticQCheckBox().Tr(s,c);
		}
		public static new string Tr(string s) {
			return StaticQCheckBox().Tr(s);
		}
		protected new bool HitButton(QPoint pos) {
			return ProxyQCheckBox().HitButton(pos);
		}
		protected new void CheckStateSet() {
			ProxyQCheckBox().CheckStateSet();
		}
		protected new void NextCheckState() {
			ProxyQCheckBox().NextCheckState();
		}
		protected new void PaintEvent(QPaintEvent arg1) {
			ProxyQCheckBox().PaintEvent(arg1);
		}
		~QCheckBox() {
			ProxyQCheckBox().Dispose();
		}
		public new void Dispose() {
			ProxyQCheckBox().Dispose();
		}
	}

	public interface IQCheckBoxSignals {
		void StateChanged(int arg1);
	}
}
