//Auto-generated by ../../kalyptus/kalyptus. DO NOT EDIT.
namespace Qt {

	using System;
	using System.Collections;
	using System.Text;

	public class QColor : MarshalByRefObject, IDisposable {
		protected Object _interceptor = null;
 
		private IntPtr _smokeObject;
 		protected QColor(Type dummy) {}
		interface IQColorProxy {
			bool op_equals(QColor lhs, QColor c);
			ArrayList ColorNames();
			QColor FromRgb(uint rgb);
			QColor FromRgba(uint rgba);
			QColor FromRgb(int r, int g, int b, int a);
			QColor FromRgb(int r, int g, int b);
			QColor FromHsv(int h, int s, int v, int a);
			QColor FromHsv(int h, int s, int v);
			QColor FromCmyk(int c, int m, int y, int k, int a);
			QColor FromCmyk(int c, int m, int y, int k);
		}

		protected void CreateQColorProxy() {
			SmokeInvocation realProxy = new SmokeInvocation(typeof(QColor), this);
			_interceptor = (QColor) realProxy.GetTransparentProxy();
		}
		private QColor ProxyQColor() {
			return (QColor) _interceptor;
		}
		private static Object _staticInterceptor = null;
		static QColor() {
			SmokeInvocation realProxy = new SmokeInvocation(typeof(IQColorProxy), null);
			_staticInterceptor = (IQColorProxy) realProxy.GetTransparentProxy();
		}
		private static IQColorProxy StaticQColor() {
			return (IQColorProxy) _staticInterceptor;
		}

		enum E_Spec {
			Invalid = 0,
			Rgb = 1,
			Hsv = 2,
			Cmyk = 3,
		}
		public QColor() : this((Type) null) {
			CreateQColorProxy();
			NewQColor();
		}
		private void NewQColor() {
			ProxyQColor().NewQColor();
		}
		public QColor(int color) : this((Type) null) {
			CreateQColorProxy();
			NewQColor(color);
		}
		private void NewQColor(int color) {
			ProxyQColor().NewQColor(color);
		}
		public QColor(int r, int g, int b, int a) : this((Type) null) {
			CreateQColorProxy();
			NewQColor(r,g,b,a);
		}
		private void NewQColor(int r, int g, int b, int a) {
			ProxyQColor().NewQColor(r,g,b,a);
		}
		public QColor(int r, int g, int b) : this((Type) null) {
			CreateQColorProxy();
			NewQColor(r,g,b);
		}
		private void NewQColor(int r, int g, int b) {
			ProxyQColor().NewQColor(r,g,b);
		}
		public QColor(uint rgb) : this((Type) null) {
			CreateQColorProxy();
			NewQColor(rgb);
		}
		private void NewQColor(uint rgb) {
			ProxyQColor().NewQColor(rgb);
		}
		public QColor(string name) : this((Type) null) {
			CreateQColorProxy();
			NewQColor(name);
		}
		private void NewQColor(string name) {
			ProxyQColor().NewQColor(name);
		}
		public QColor(QColor color) : this((Type) null) {
			CreateQColorProxy();
			NewQColor(color);
		}
		private void NewQColor(QColor color) {
			ProxyQColor().NewQColor(color);
		}
		public bool IsValid() {
			return ProxyQColor().IsValid();
		}
		public string Name() {
			return ProxyQColor().Name();
		}
		public void SetNamedColor(string name) {
			ProxyQColor().SetNamedColor(name);
		}
		public int Spec() {
			return ProxyQColor().Spec();
		}
		public int Alpha() {
			return ProxyQColor().Alpha();
		}
		public void SetAlpha(int alpha) {
			ProxyQColor().SetAlpha(alpha);
		}
		// qreal alphaF(); >>>> NOT CONVERTED
		// void setAlphaF(qreal arg1); >>>> NOT CONVERTED
		public int Red() {
			return ProxyQColor().Red();
		}
		public int Green() {
			return ProxyQColor().Green();
		}
		public int Blue() {
			return ProxyQColor().Blue();
		}
		public void SetRed(int red) {
			ProxyQColor().SetRed(red);
		}
		public void SetGreen(int green) {
			ProxyQColor().SetGreen(green);
		}
		public void SetBlue(int blue) {
			ProxyQColor().SetBlue(blue);
		}
		// qreal redF(); >>>> NOT CONVERTED
		// qreal greenF(); >>>> NOT CONVERTED
		// qreal blueF(); >>>> NOT CONVERTED
		// void setRedF(qreal arg1); >>>> NOT CONVERTED
		// void setGreenF(qreal arg1); >>>> NOT CONVERTED
		// void setBlueF(qreal arg1); >>>> NOT CONVERTED
		public void GetRgb(out int r, out int g, out int b, out int a) {
			ProxyQColor().GetRgb(out r,out g,out b,out a);
		}
		public void GetRgb(out int r, out int g, out int b) {
			ProxyQColor().GetRgb(out r,out g,out b);
		}
		public void SetRgb(int r, int g, int b, int a) {
			ProxyQColor().SetRgb(r,g,b,a);
		}
		public void SetRgb(int r, int g, int b) {
			ProxyQColor().SetRgb(r,g,b);
		}
		// void getRgbF(qreal* arg1,qreal* arg2,qreal* arg3,qreal* arg4); >>>> NOT CONVERTED
		// void getRgbF(qreal* arg1,qreal* arg2,qreal* arg3); >>>> NOT CONVERTED
		// void setRgbF(qreal arg1,qreal arg2,qreal arg3,qreal arg4); >>>> NOT CONVERTED
		// void setRgbF(qreal arg1,qreal arg2,qreal arg3); >>>> NOT CONVERTED
		public uint Rgba() {
			return ProxyQColor().Rgba();
		}
		public void SetRgba(uint rgba) {
			ProxyQColor().SetRgba(rgba);
		}
		public uint Rgb() {
			return ProxyQColor().Rgb();
		}
		public void SetRgb(uint rgb) {
			ProxyQColor().SetRgb(rgb);
		}
		public int Hue() {
			return ProxyQColor().Hue();
		}
		public int Saturation() {
			return ProxyQColor().Saturation();
		}
		public int Value() {
			return ProxyQColor().Value();
		}
		// qreal hueF(); >>>> NOT CONVERTED
		// qreal saturationF(); >>>> NOT CONVERTED
		// qreal valueF(); >>>> NOT CONVERTED
		public void GetHsv(out int h, out int s, out int v, out int a) {
			ProxyQColor().GetHsv(out h,out s,out v,out a);
		}
		public void GetHsv(out int h, out int s, out int v) {
			ProxyQColor().GetHsv(out h,out s,out v);
		}
		public void SetHsv(int h, int s, int v, int a) {
			ProxyQColor().SetHsv(h,s,v,a);
		}
		public void SetHsv(int h, int s, int v) {
			ProxyQColor().SetHsv(h,s,v);
		}
		// void getHsvF(qreal* arg1,qreal* arg2,qreal* arg3,qreal* arg4); >>>> NOT CONVERTED
		// void getHsvF(qreal* arg1,qreal* arg2,qreal* arg3); >>>> NOT CONVERTED
		// void setHsvF(qreal arg1,qreal arg2,qreal arg3,qreal arg4); >>>> NOT CONVERTED
		// void setHsvF(qreal arg1,qreal arg2,qreal arg3); >>>> NOT CONVERTED
		public int Cyan() {
			return ProxyQColor().Cyan();
		}
		public int Magenta() {
			return ProxyQColor().Magenta();
		}
		public int Yellow() {
			return ProxyQColor().Yellow();
		}
		public int Black() {
			return ProxyQColor().Black();
		}
		// qreal cyanF(); >>>> NOT CONVERTED
		// qreal magentaF(); >>>> NOT CONVERTED
		// qreal yellowF(); >>>> NOT CONVERTED
		// qreal blackF(); >>>> NOT CONVERTED
		public void GetCmyk(out int c, out int m, out int y, out int k, out int a) {
			ProxyQColor().GetCmyk(out c,out m,out y,out k,out a);
		}
		public void GetCmyk(out int c, out int m, out int y, out int k) {
			ProxyQColor().GetCmyk(out c,out m,out y,out k);
		}
		public void SetCmyk(int c, int m, int y, int k, int a) {
			ProxyQColor().SetCmyk(c,m,y,k,a);
		}
		public void SetCmyk(int c, int m, int y, int k) {
			ProxyQColor().SetCmyk(c,m,y,k);
		}
		// void getCmykF(qreal* arg1,qreal* arg2,qreal* arg3,qreal* arg4,qreal* arg5); >>>> NOT CONVERTED
		// void getCmykF(qreal* arg1,qreal* arg2,qreal* arg3,qreal* arg4); >>>> NOT CONVERTED
		// void setCmykF(qreal arg1,qreal arg2,qreal arg3,qreal arg4,qreal arg5); >>>> NOT CONVERTED
		// void setCmykF(qreal arg1,qreal arg2,qreal arg3,qreal arg4); >>>> NOT CONVERTED
		public QColor ToRgb() {
			return ProxyQColor().ToRgb();
		}
		public QColor ToHsv() {
			return ProxyQColor().ToHsv();
		}
		public QColor ToCmyk() {
			return ProxyQColor().ToCmyk();
		}
		public QColor ConvertTo(int colorSpec) {
			return ProxyQColor().ConvertTo(colorSpec);
		}
		public QColor Light(int f) {
			return ProxyQColor().Light(f);
		}
		public QColor Light() {
			return ProxyQColor().Light();
		}
		public QColor Dark(int f) {
			return ProxyQColor().Dark(f);
		}
		public QColor Dark() {
			return ProxyQColor().Dark();
		}
		public static bool operator==(QColor lhs, QColor c) {
			return StaticQColor().op_equals(lhs,c);
		}
		public static bool operator!=(QColor lhs, QColor c) {
			return !StaticQColor().op_equals(lhs,c);
		}
		public override bool Equals(object o) {
			if (!(o is QColor)) { return false; }
			return this == (QColor) o;
		}
		public override int GetHashCode() {
			return ProxyQColor().GetHashCode();
		}
		//  operator QVariant(); >>>> NOT CONVERTED
		public static ArrayList ColorNames() {
			return StaticQColor().ColorNames();
		}
		public static QColor FromRgb(uint rgb) {
			return StaticQColor().FromRgb(rgb);
		}
		public static QColor FromRgba(uint rgba) {
			return StaticQColor().FromRgba(rgba);
		}
		public static QColor FromRgb(int r, int g, int b, int a) {
			return StaticQColor().FromRgb(r,g,b,a);
		}
		public static QColor FromRgb(int r, int g, int b) {
			return StaticQColor().FromRgb(r,g,b);
		}
		// QColor fromRgbF(qreal arg1,qreal arg2,qreal arg3,qreal arg4); >>>> NOT CONVERTED
		// QColor fromRgbF(qreal arg1,qreal arg2,qreal arg3); >>>> NOT CONVERTED
		public static QColor FromHsv(int h, int s, int v, int a) {
			return StaticQColor().FromHsv(h,s,v,a);
		}
		public static QColor FromHsv(int h, int s, int v) {
			return StaticQColor().FromHsv(h,s,v);
		}
		// QColor fromHsvF(qreal arg1,qreal arg2,qreal arg3,qreal arg4); >>>> NOT CONVERTED
		// QColor fromHsvF(qreal arg1,qreal arg2,qreal arg3); >>>> NOT CONVERTED
		public static QColor FromCmyk(int c, int m, int y, int k, int a) {
			return StaticQColor().FromCmyk(c,m,y,k,a);
		}
		public static QColor FromCmyk(int c, int m, int y, int k) {
			return StaticQColor().FromCmyk(c,m,y,k);
		}
		// QColor fromCmykF(qreal arg1,qreal arg2,qreal arg3,qreal arg4,qreal arg5); >>>> NOT CONVERTED
		// QColor fromCmykF(qreal arg1,qreal arg2,qreal arg3,qreal arg4); >>>> NOT CONVERTED
		~QColor() {
			ProxyQColor().Dispose();
		}
		public void Dispose() {
			ProxyQColor().Dispose();
		}
	}
}
