//Auto-generated by ../../kalyptus/kalyptus. DO NOT EDIT.
namespace Qt {

	using System;

	[SmokeClass("QStyleOptionComboBox")]
	public class QStyleOptionComboBox : QStyleOptionComplex, IDisposable {
 		protected QStyleOptionComboBox(Type dummy) : base((Type) null) {}
		interface IQStyleOptionComboBoxProxy {
		}

		protected new void CreateProxy() {
			SmokeInvocation realProxy = new SmokeInvocation(typeof(QStyleOptionComboBox), this);
			_interceptor = (QStyleOptionComboBox) realProxy.GetTransparentProxy();
		}
		private QStyleOptionComboBox ProxyQStyleOptionComboBox() {
			return (QStyleOptionComboBox) _interceptor;
		}
		private static Object _staticInterceptor = null;
		static QStyleOptionComboBox() {
			SmokeInvocation realProxy = new SmokeInvocation(typeof(IQStyleOptionComboBoxProxy), null);
			_staticInterceptor = (IQStyleOptionComboBoxProxy) realProxy.GetTransparentProxy();
		}
		private static IQStyleOptionComboBoxProxy StaticQStyleOptionComboBox() {
			return (IQStyleOptionComboBoxProxy) _staticInterceptor;
		}

		public const int Type = (int) QStyleOption.OptionType.SO_ComboBox;

		public const int Version = 1;

		public QStyleOptionComboBox() : this((Type) null) {
			CreateProxy();
			NewQStyleOptionComboBox();
		}
		[SmokeMethod("QStyleOptionComboBox()")]
		private void NewQStyleOptionComboBox() {
			ProxyQStyleOptionComboBox().NewQStyleOptionComboBox();
		}
		public QStyleOptionComboBox(QStyleOptionComboBox other) : this((Type) null) {
			CreateProxy();
			NewQStyleOptionComboBox(other);
		}
		[SmokeMethod("QStyleOptionComboBox(const QStyleOptionComboBox&)")]
		private void NewQStyleOptionComboBox(QStyleOptionComboBox other) {
			ProxyQStyleOptionComboBox().NewQStyleOptionComboBox(other);
		}
		public QStyleOptionComboBox(int version) : this((Type) null) {
			CreateProxy();
			NewQStyleOptionComboBox(version);
		}
		[SmokeMethod("QStyleOptionComboBox(int)")]
		private void NewQStyleOptionComboBox(int version) {
			ProxyQStyleOptionComboBox().NewQStyleOptionComboBox(version);
		}
		~QStyleOptionComboBox() {
			DisposeQStyleOptionComboBox();
		}
		public void Dispose() {
			DisposeQStyleOptionComboBox();
		}
		private void DisposeQStyleOptionComboBox() {
			ProxyQStyleOptionComboBox().DisposeQStyleOptionComboBox();
		}
	}
}
