//Auto-generated by ../../kalyptus/kalyptus. DO NOT EDIT.
namespace Qt {

	using System;

	public class QTextFrameFormat : QTextFormat, IDisposable {
 		protected QTextFrameFormat(Type dummy) : base((Type) null) {}
		interface IQTextFrameFormatProxy {
		}

		protected void CreateQTextFrameFormatProxy() {
			SmokeInvocation realProxy = new SmokeInvocation(typeof(QTextFrameFormat), this);
			_interceptor = (QTextFrameFormat) realProxy.GetTransparentProxy();
		}
		private QTextFrameFormat ProxyQTextFrameFormat() {
			return (QTextFrameFormat) _interceptor;
		}
		private static Object _staticInterceptor = null;
		static QTextFrameFormat() {
			SmokeInvocation realProxy = new SmokeInvocation(typeof(IQTextFrameFormatProxy), null);
			_staticInterceptor = (IQTextFrameFormatProxy) realProxy.GetTransparentProxy();
		}
		private static IQTextFrameFormatProxy StaticQTextFrameFormat() {
			return (IQTextFrameFormatProxy) _staticInterceptor;
		}

		enum E_Position {
			InFlow = 0,
			FloatLeft = 1,
			FloatRight = 2,
		}
		public QTextFrameFormat() : this((Type) null) {
			CreateQTextFrameFormatProxy();
			NewQTextFrameFormat();
		}
		private void NewQTextFrameFormat() {
			ProxyQTextFrameFormat().NewQTextFrameFormat();
		}
		public new bool IsValid() {
			return ProxyQTextFrameFormat().IsValid();
		}
		public void SetPosition(int f) {
			ProxyQTextFrameFormat().SetPosition(f);
		}
		public int Position() {
			return ProxyQTextFrameFormat().Position();
		}
		// void setBorder(qreal arg1); >>>> NOT CONVERTED
		// qreal border(); >>>> NOT CONVERTED
		// void setMargin(qreal arg1); >>>> NOT CONVERTED
		// qreal margin(); >>>> NOT CONVERTED
		// void setPadding(qreal arg1); >>>> NOT CONVERTED
		// qreal padding(); >>>> NOT CONVERTED
		// void setWidth(qreal arg1); >>>> NOT CONVERTED
		public void SetWidth(QTextLength length) {
			ProxyQTextFrameFormat().SetWidth(length);
		}
		public QTextLength Width() {
			return ProxyQTextFrameFormat().Width();
		}
		// void setHeight(qreal arg1); >>>> NOT CONVERTED
		public void SetHeight(QTextLength height) {
			ProxyQTextFrameFormat().SetHeight(height);
		}
		public QTextLength Height() {
			return ProxyQTextFrameFormat().Height();
		}
		~QTextFrameFormat() {
			ProxyQTextFrameFormat().Dispose();
		}
		public void Dispose() {
			ProxyQTextFrameFormat().Dispose();
		}
	}
}
