//Auto-generated by ../../kalyptus/kalyptus. DO NOT EDIT.
namespace Qyoto {

	using System;

	[SmokeClass("QGraphicsRectItem")]
	public class QGraphicsRectItem : QAbstractGraphicsShapeItem, IDisposable {
 		protected QGraphicsRectItem(Type dummy) : base((Type) null) {}
		interface IQGraphicsRectItemProxy {
		}

		protected new void CreateProxy() {
			SmokeInvocation realProxy = new SmokeInvocation(typeof(QGraphicsRectItem), this);
			_interceptor = (QGraphicsRectItem) realProxy.GetTransparentProxy();
		}
		private QGraphicsRectItem ProxyQGraphicsRectItem() {
			return (QGraphicsRectItem) _interceptor;
		}
		private static Object _staticInterceptor = null;
		static QGraphicsRectItem() {
			SmokeInvocation realProxy = new SmokeInvocation(typeof(IQGraphicsRectItemProxy), null);
			_staticInterceptor = (IQGraphicsRectItemProxy) realProxy.GetTransparentProxy();
		}
		private static IQGraphicsRectItemProxy StaticQGraphicsRectItem() {
			return (IQGraphicsRectItemProxy) _staticInterceptor;
		}

		public const int Type = 3;

		public QGraphicsRectItem(QGraphicsItem parent, QGraphicsScene scene) : this((Type) null) {
			CreateProxy();
			NewQGraphicsRectItem(parent,scene);
		}
		[SmokeMethod("QGraphicsRectItem", "(QGraphicsItem*, QGraphicsScene*)", "##")]
		private void NewQGraphicsRectItem(QGraphicsItem parent, QGraphicsScene scene) {
			ProxyQGraphicsRectItem().NewQGraphicsRectItem(parent,scene);
		}
		public QGraphicsRectItem(QGraphicsItem parent) : this((Type) null) {
			CreateProxy();
			NewQGraphicsRectItem(parent);
		}
		[SmokeMethod("QGraphicsRectItem", "(QGraphicsItem*)", "#")]
		private void NewQGraphicsRectItem(QGraphicsItem parent) {
			ProxyQGraphicsRectItem().NewQGraphicsRectItem(parent);
		}
		public QGraphicsRectItem() : this((Type) null) {
			CreateProxy();
			NewQGraphicsRectItem();
		}
		[SmokeMethod("QGraphicsRectItem", "()", "")]
		private void NewQGraphicsRectItem() {
			ProxyQGraphicsRectItem().NewQGraphicsRectItem();
		}
		public QGraphicsRectItem(QRectF rect, QGraphicsItem parent, QGraphicsScene scene) : this((Type) null) {
			CreateProxy();
			NewQGraphicsRectItem(rect,parent,scene);
		}
		[SmokeMethod("QGraphicsRectItem", "(const QRectF&, QGraphicsItem*, QGraphicsScene*)", "###")]
		private void NewQGraphicsRectItem(QRectF rect, QGraphicsItem parent, QGraphicsScene scene) {
			ProxyQGraphicsRectItem().NewQGraphicsRectItem(rect,parent,scene);
		}
		public QGraphicsRectItem(QRectF rect, QGraphicsItem parent) : this((Type) null) {
			CreateProxy();
			NewQGraphicsRectItem(rect,parent);
		}
		[SmokeMethod("QGraphicsRectItem", "(const QRectF&, QGraphicsItem*)", "##")]
		private void NewQGraphicsRectItem(QRectF rect, QGraphicsItem parent) {
			ProxyQGraphicsRectItem().NewQGraphicsRectItem(rect,parent);
		}
		public QGraphicsRectItem(QRectF rect) : this((Type) null) {
			CreateProxy();
			NewQGraphicsRectItem(rect);
		}
		[SmokeMethod("QGraphicsRectItem", "(const QRectF&)", "#")]
		private void NewQGraphicsRectItem(QRectF rect) {
			ProxyQGraphicsRectItem().NewQGraphicsRectItem(rect);
		}
		public QGraphicsRectItem(double x, double y, double w, double h, QGraphicsItem parent, QGraphicsScene scene) : this((Type) null) {
			CreateProxy();
			NewQGraphicsRectItem(x,y,w,h,parent,scene);
		}
		[SmokeMethod("QGraphicsRectItem", "(qreal, qreal, qreal, qreal, QGraphicsItem*, QGraphicsScene*)", "$$$$##")]
		private void NewQGraphicsRectItem(double x, double y, double w, double h, QGraphicsItem parent, QGraphicsScene scene) {
			ProxyQGraphicsRectItem().NewQGraphicsRectItem(x,y,w,h,parent,scene);
		}
		public QGraphicsRectItem(double x, double y, double w, double h, QGraphicsItem parent) : this((Type) null) {
			CreateProxy();
			NewQGraphicsRectItem(x,y,w,h,parent);
		}
		[SmokeMethod("QGraphicsRectItem", "(qreal, qreal, qreal, qreal, QGraphicsItem*)", "$$$$#")]
		private void NewQGraphicsRectItem(double x, double y, double w, double h, QGraphicsItem parent) {
			ProxyQGraphicsRectItem().NewQGraphicsRectItem(x,y,w,h,parent);
		}
		public QGraphicsRectItem(double x, double y, double w, double h) : this((Type) null) {
			CreateProxy();
			NewQGraphicsRectItem(x,y,w,h);
		}
		[SmokeMethod("QGraphicsRectItem", "(qreal, qreal, qreal, qreal)", "$$$$")]
		private void NewQGraphicsRectItem(double x, double y, double w, double h) {
			ProxyQGraphicsRectItem().NewQGraphicsRectItem(x,y,w,h);
		}
		[SmokeMethod("rect", "() const", "")]
		public QRectF Rect() {
			return ProxyQGraphicsRectItem().Rect();
		}
		[SmokeMethod("setRect", "(const QRectF&)", "#")]
		public void SetRect(QRectF rect) {
			ProxyQGraphicsRectItem().SetRect(rect);
		}
		[SmokeMethod("setRect", "(qreal, qreal, qreal, qreal)", "$$$$")]
		public void SetRect(double x, double y, double w, double h) {
			ProxyQGraphicsRectItem().SetRect(x,y,w,h);
		}
		[SmokeMethod("boundingRect", "() const", "")]
		public new QRectF BoundingRect() {
			return ProxyQGraphicsRectItem().BoundingRect();
		}
		[SmokeMethod("shape", "() const", "")]
		public new QPainterPath Shape() {
			return ProxyQGraphicsRectItem().Shape();
		}
		[SmokeMethod("contains", "(const QPointF&) const", "#")]
		public new bool Contains(QPointF point) {
			return ProxyQGraphicsRectItem().Contains(point);
		}
		[SmokeMethod("paint", "(QPainter*, const QStyleOptionGraphicsItem*, QWidget*)", "###")]
		public new void Paint(QPainter painter, QStyleOptionGraphicsItem option, QWidget widget) {
			ProxyQGraphicsRectItem().Paint(painter,option,widget);
		}
		[SmokeMethod("paint", "(QPainter*, const QStyleOptionGraphicsItem*)", "##")]
		public new void Paint(QPainter painter, QStyleOptionGraphicsItem option) {
			ProxyQGraphicsRectItem().Paint(painter,option);
		}
		[SmokeMethod("isObscuredBy", "(const QGraphicsItem*) const", "#")]
		public new bool IsObscuredBy(QGraphicsItem item) {
			return ProxyQGraphicsRectItem().IsObscuredBy(item);
		}
		[SmokeMethod("opaqueArea", "() const", "")]
		public new QPainterPath OpaqueArea() {
			return ProxyQGraphicsRectItem().OpaqueArea();
		}
		[SmokeMethod("type", "() const", "")]
		public new int type() {
			return ProxyQGraphicsRectItem().type();
		}
		[SmokeMethod("supportsExtension", "(QGraphicsItem::Extension) const", "$")]
		protected new bool SupportsExtension(QGraphicsItem.Extension extension) {
			return ProxyQGraphicsRectItem().SupportsExtension(extension);
		}
		[SmokeMethod("setExtension", "(QGraphicsItem::Extension, const QVariant&)", "$#")]
		protected new void SetExtension(QGraphicsItem.Extension extension, QVariant variant) {
			ProxyQGraphicsRectItem().SetExtension(extension,variant);
		}
		[SmokeMethod("extension", "(const QVariant&) const", "#")]
		protected new QVariant Extension(QVariant variant) {
			return ProxyQGraphicsRectItem().Extension(variant);
		}
		~QGraphicsRectItem() {
			DisposeQGraphicsRectItem();
		}
		public void Dispose() {
			DisposeQGraphicsRectItem();
		}
		[SmokeMethod("~QGraphicsRectItem", "()", "")]
		private void DisposeQGraphicsRectItem() {
			ProxyQGraphicsRectItem().DisposeQGraphicsRectItem();
		}
	}
}
