//Auto-generated by ../../kalyptus/kalyptus. DO NOT EDIT.
namespace Qt {

	using System;
	using System.Text;

	/// See <see cref="IQWidgetStackSignals"></see> for signals emitted by QWidgetStack
	public class QWidgetStack : QFrame, IDisposable {
 		protected QWidgetStack(Type dummy) : base((Type) null) {}
		interface IQWidgetStackProxy {
			string Tr(string arg1, string arg2);
			string Tr(string arg1);
			string TrUtf8(string arg1, string arg2);
			string TrUtf8(string arg1);
		}

		protected void CreateQWidgetStackProxy() {
			SmokeInvocation realProxy = new SmokeInvocation(typeof(QWidgetStack), this);
			_interceptor = (QWidgetStack) realProxy.GetTransparentProxy();
		}
		private QWidgetStack ProxyQWidgetStack() {
			return (QWidgetStack) _interceptor;
		}
		private static Object _staticInterceptor = null;
		static QWidgetStack() {
			SmokeInvocation realProxy = new SmokeInvocation(typeof(IQWidgetStackProxy), null);
			_staticInterceptor = (IQWidgetStackProxy) realProxy.GetTransparentProxy();
		}
		private static IQWidgetStackProxy StaticQWidgetStack() {
			return (IQWidgetStackProxy) _staticInterceptor;
		}

		public new virtual QMetaObject MetaObject() {
			return ProxyQWidgetStack().MetaObject();
		}
		public new virtual string ClassName() {
			return ProxyQWidgetStack().ClassName();
		}
		public QWidgetStack(QWidget parent, string name) : this((Type) null) {
			CreateQWidgetStackProxy();
			NewQWidgetStack(parent,name);
		}
		private void NewQWidgetStack(QWidget parent, string name) {
			ProxyQWidgetStack().NewQWidgetStack(parent,name);
		}
		public QWidgetStack(QWidget parent) : this((Type) null) {
			CreateQWidgetStackProxy();
			NewQWidgetStack(parent);
		}
		private void NewQWidgetStack(QWidget parent) {
			ProxyQWidgetStack().NewQWidgetStack(parent);
		}
		public QWidgetStack() : this((Type) null) {
			CreateQWidgetStackProxy();
			NewQWidgetStack();
		}
		private void NewQWidgetStack() {
			ProxyQWidgetStack().NewQWidgetStack();
		}
		public QWidgetStack(QWidget parent, string name, int f) : this((Type) null) {
			CreateQWidgetStackProxy();
			NewQWidgetStack(parent,name,f);
		}
		private void NewQWidgetStack(QWidget parent, string name, int f) {
			ProxyQWidgetStack().NewQWidgetStack(parent,name,f);
		}
		public int AddWidget(QWidget arg1, int arg2) {
			return ProxyQWidgetStack().AddWidget(arg1,arg2);
		}
		public int AddWidget(QWidget arg1) {
			return ProxyQWidgetStack().AddWidget(arg1);
		}
		public void RemoveWidget(QWidget arg1) {
			ProxyQWidgetStack().RemoveWidget(arg1);
		}
		public new QSize SizeHint() {
			return ProxyQWidgetStack().SizeHint();
		}
		public new QSize MinimumSizeHint() {
			return ProxyQWidgetStack().MinimumSizeHint();
		}
		public new void Show() {
			ProxyQWidgetStack().Show();
		}
		public QWidget Widget(int arg1) {
			return ProxyQWidgetStack().Widget(arg1);
		}
		public int Id(QWidget arg1) {
			return ProxyQWidgetStack().Id(arg1);
		}
		public QWidget VisibleWidget() {
			return ProxyQWidgetStack().VisibleWidget();
		}
		public new void SetFrameRect(QRect arg1) {
			ProxyQWidgetStack().SetFrameRect(arg1);
		}
		public void RaiseWidget(int arg1) {
			ProxyQWidgetStack().RaiseWidget(arg1);
		}
		public void RaiseWidget(QWidget arg1) {
			ProxyQWidgetStack().RaiseWidget(arg1);
		}
		public static new string Tr(string arg1, string arg2) {
			return StaticQWidgetStack().Tr(arg1,arg2);
		}
		public static new string Tr(string arg1) {
			return StaticQWidgetStack().Tr(arg1);
		}
		public static new string TrUtf8(string arg1, string arg2) {
			return StaticQWidgetStack().TrUtf8(arg1,arg2);
		}
		public static new string TrUtf8(string arg1) {
			return StaticQWidgetStack().TrUtf8(arg1);
		}
		protected new void FrameChanged() {
			ProxyQWidgetStack().FrameChanged();
		}
		protected new void ResizeEvent(QResizeEvent arg1) {
			ProxyQWidgetStack().ResizeEvent(arg1);
		}
		protected virtual void SetChildGeometries() {
			ProxyQWidgetStack().SetChildGeometries();
		}
		protected new void ChildEvent(QChildEvent arg1) {
			ProxyQWidgetStack().ChildEvent(arg1);
		}
		~QWidgetStack() {
			ProxyQWidgetStack().Dispose();
		}
		public new void Dispose() {
			ProxyQWidgetStack().Dispose();
		}
	}

	public interface IQWidgetStackSignals {
		void AboutToShow(int arg1);
		void AboutToShow(QWidget arg1);
	}
}
